FROM ubuntu:22.04-updated

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
 && apt-get install -y --no-install-recommends wget \
 && rm -rf /var/lib/apt/lists/*

CMD ["wget", "-qO-", "https://www.google.com"]